# Generated by Django 4.2.7 on 2023-11-21 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerva', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='integra',
            new_name='Avisos',
        ),
        migrations.AlterModelOptions(
            name='avisos',
            options={},
        ),
    ]
